### ISSUE TITLE
The script doesn't apply to jobs

### ISSUE THREAD

**Issue by mohamed2m2018** [feder-cr/Auto_Jobs_Applier_AIHawk#137] opened 2024-08-29 16:04 UTC
<img width="1023" alt="Screenshot 2024-08-29 at 7 06 38 PM" src="https://github.com/user-attachments/assets/586d6336-33fc-4181-befb-24f4f2053318">
I got this logs, but the script just scrolls down the jobs and doesn't apply to any

**Comment by cwilby** [comment] 2024-08-29 16:06
fyi, i've saved the stars list on this repo.
if we're ever hiring, i'm matching your github username against that list.

**Comment by iliasjaddi** [comment] 2024-08-29 16:13
Me too!

**Comment by feder-cr** [comment] 2024-08-29 17:16
so strange

**Comment by feder-cr** [comment] 2024-08-29 17:22
check your openai balance

**Comment by iliasjaddi** [comment] 2024-08-29 18:00
I have enough openai balance.
<img width="582" alt="imagen" src="https://github.com/user-attachments/assets/aaa982ce-d87f-4bc5-afb1-aa96af31bb47">
The problem is that it only keeps scrolling the jobs but doesn't apply to any!

**Comment by reneekharat** [comment] 2024-08-29 18:01
same problem here, and I have enough on openai as well

**Comment by pafthinder** [comment] 2024-08-29 20:35
yeah, it doesn't get to the point of using OpenAI API ; it doesn't find any job. 
It looks like class names of HTML elements are misaligned 

@feder-cr check the issue 
https://github.com/feder-cr/linkedIn_auto_jobs_applier_with_AI/issues/114 

I am thinking maybe it's because I have LI learning subscription and this changes whole layout? 
@reneekharat do you have LI premium or LI learning subscription?

**Comment by Andres-Ventura** [comment] 2024-08-29 20:50
testing it now

**Comment by Andres-Ventura** [comment] 2024-08-29 20:51
I can work on this if you want @feder-cr

**Comment by Andres-Ventura** [comment] 2024-08-29 20:57
update: heres the line causing the issue mates


`   utils.printyellow(f"Starting job list process") <--- I printed this
        job_list_elements = self.driver.find_elements(By.CLASS_NAME, 'scaffold-layout__list-container')[0].find_elements(By.CLASS_NAME, 'jobs-search-results__list-item')
`

**Comment by B-Chaudhry** [comment] 2024-08-29 21:19
I am facing the same problem

**Comment by reneekharat** [comment] 2024-08-29 21:41
> yeah, it doesn't get to the point of using OpenAI API ; it doesn't find any job. It looks like class names of HTML elements are misaligned
> 
> @feder-cr check the issue #114
> 
> I am thinking maybe it's because I have LI learning subscription and this changes whole layout? @reneekharat do you have LI premium or LI learning subscription?

no I have the standard. previously had premium though, not sure if that changes anything

**Comment by pafthinder** [comment] 2024-08-29 22:44
@reneekharat damn, it's bad. because there is no pattern now. you have standard account like people for whom bot works. 
so this is not the issue with the layout I would say 

@Andres-Ventura ; yeah, I figured it out as well in #114 ; check it out please, I have put there some additional comments. Got any idea what to do with it?

**Comment by feder-cr** [comment] 2024-09-03 16:01
@Andres-Ventura yes for sure bro!

**Comment by Andres-Ventura** [comment] 2024-09-03 17:57
Update:  the issue lies inside the extract_job_information_from_tile function inside file"linkedin_job_manager.py" where a few  find_element() references are not being referenced correctly.

**Comment by naganikshith04** [comment] 2024-09-03 23:19
Any update on the fix?

**Comment by Andres-Ventura** [comment] 2024-09-03 23:31
Got it to work locally. running some tests

**Comment by naganikshith04** [comment] 2024-09-04 00:14
Please let me know, what would the fix for it

**Comment by naganikshith04** [comment] 2024-09-04 15:15
[image: image.png]

Same, didn't get solved for me.

**Comment by SaadKhalidAlarifi** [comment] 2024-09-04 19:33
I am having the same issue (Applying to AU jobs)

**Comment by pafthinder** [comment] 2024-09-05 13:29
try checking #114

**Comment by feder-cr** [comment] 2024-09-08 22:54
@Andres-Ventura any update?

**Comment by pafthinder** [comment] 2024-09-09 05:44
@feder-cr why would u close #114 without resolving it and asking about solution from community in other issue? let's merge those to one and keep it open, as you can see this is issue affecting a lot of people using the bot 

I managed to make bot running in my environment in #114 but it doesn't mean the issue is solved. App on the whole still works bad and it requires loads of work - collaborative effort

**Comment by feder-cr** [comment] 2024-09-12 23:37
@pafthinder sorry

**Comment by pushpixels** [comment] 2024-09-13 16:38
Any fix?...

**Comment by RahulSinghalChicago** [comment] 2024-09-15 01:38
Here's the code that I'm using for the fix. Replace the method in linkedin_job_manager.py

@feder-cr let me know if you want a PR

`    def extract_job_information_from_tile(self, job_tile):
        job_title, company, job_location, apply_method, link = "", "", "", "", ""
        try:
            # job_title = job_tile.find_element(By.CLASS_NAME, 'job-card-list__title').text
            # link = job_tile.find_element(By.CLASS_NAME, 'job-card-list__title').get_attribute('href').split('?')[0]
            # company = job_tile.find_element(By.CLASS_NAME, 'job-card-container__primary-description').text
            job_title = job_tile.find_element(By.CLASS_NAME, 'job-card-job-posting-card-wrapper__title').text            
            link = job_tile.find_element(By.CLASS_NAME, 'job-card-job-posting-card-wrapper__card-link').get_attribute('href').split('currentJobId=')[1].split('&')[0]
            link = "https://www.linkedin.com/jobs/view/" + link            
            company = job_tile.find_element(By.CLASS_NAME, 'artdeco-entity-lockup__subtitle ').text
        except:
            print("except")
            print(job_title, company, job_location, link, apply_method)
            pass
        try:
            # job_location = job_tile.find_element(By.CLASS_NAME, 'job-card-container__metadata-item').text
            job_location = job_tile.find_element(By.CLASS_NAME, 'artdeco-entity-lockup__subtitle ember-view').text
        except:
            pass
        try:
            # apply_method = job_tile.find_element(By.CLASS_NAME, 'job-card-container__apply-method').text
            apply_method = job_tile.find_element(By.CLASS_NAME, 'job-card-job-posting-card-wrapper__footer-item').text
        except:
            apply_method = "Applied"

        return job_title, company, job_location, link, apply_method
`

**Comment by iwnfubb** [comment] 2024-09-15 07:02
The fix from @RahulSinghalChicago works for me !

**Comment by feder-cr** [comment] 2024-09-15 13:26
@RahulSinghalChicago yes for sure, join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity

**Comment by RahulSinghalChicago** [comment] 2024-09-17 05:25
fyi, the element selector reverted to the original version on my linkedin today, so the code update will allow for both.

**Comment by feder-cr** [comment] 2024-09-25 14:09
@RahulSinghalChicago please send PR

**Closed by feder-cr** 2024-09-25 14:09 UTC
Labels: bug
