### ISSUE TITLE
[NEED HELP] UNABLE TO RUN THE CODE ON MY PC 

### ISSUE THREAD

**Issue by MiamiVice305** [feder-cr/Auto_Jobs_Applier_AIHawk#650] opened 2024-10-29 01:15 UTC
### Issue summary

Effectively Running the Code issue

### Detailed description

Hello I am not tech savvy. I'm attempting to put the software/code in place so I can use it on a job application website (monster, fintalent, indeed etc.) Is there anyone I can hire/pay to run it for me for the uses i need?

### Expected outcome

I EXPECT TO FIND SOEONE I CAN PAY TO RUN THE PROGRAM FOR MY DESIRED USES

### Additional context

USING THIS PROJECT AS A STEPPING STONE TO FINDING A DEVELOPER FOR A MORE INTENSE PROFITABLE PROJECT WITH A HIGH "FOR HIRE" PRICE.

**Comment by sarob** [comment] 2024-10-29 01:42
As a project we are talking about making the work for multiple job boards. Using this open source software as a base for a commercial product is always an option. I can talk to you about it if you are interested.

**Comment by MiamiVice305** [comment] 2024-10-29 01:43
Yes, I would be interested.

**Comment by surapuramakhil** [comment] 2024-10-29 04:40
@sarob Best of my knowledge - license of this software prohibits for commercial use 

2.	Prohibition of Resale and Non-Commercial Use
The software may not be sold without explicit authorization from the original author. It is intended for non-commercial use unless specific permission for commercial use is granted.

**Comment by surapuramakhil** [comment] 2024-10-29 04:41
As this is not a bug - closing this.

ReadMe https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk/blob/main/README.md do provide links for both Telegram and Discord community where you can easily find freelancers to help you out.

**Closed by surapuramakhil** 2024-10-29 04:41 UTC
Labels: good first issue
